### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by Rlee719** [harisw/STARFM_prediction#2]
Could you offer some information about what these three input txt refers to? It is better to give some examples.

**Comment by harisw** [comment]
These three input refers to the pixel that helps to predict the specific pixel.
Here is the paper if you want to read furthermore
[Karisma_STARFM1.docx](https://github.com/harisw/STARFM_prediction/files/3799972/Karisma_STARFM1.docx)

**Comment by Rlee719** [comment]
> These three input refers to the pixel that helps to predict the specific pixel.
> Here is the paper if you want to read furthermore
> [Karisma_STARFM1.docx](https://github.com/harisw/STARFM_prediction/files/3799972/Karisma_STARFM1.docx)

Thanks for reply
